var searchData=
[
  ['n_0',['N',['../namespace_n.html',1,'']]],
  ['nsubstitute_1',['NSubstitute',['../namespace_n_substitute.html',1,'']]],
  ['nsubstitute_3a_3acallbacks_2',['Callbacks',['../namespace_n_substitute_1_1_callbacks.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3aclearextensions_3',['ClearExtensions',['../namespace_n_substitute_1_1_clear_extensions.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3acompatibility_4',['Compatibility',['../namespace_n_substitute_1_1_compatibility.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3acore_5',['Core',['../namespace_n_substitute_1_1_core.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3acore_3a_3aarguments_6',['Arguments',['../namespace_n_substitute_1_1_core_1_1_arguments.html',1,'NSubstitute::Core']]],
  ['nsubstitute_3a_3acore_3a_3adependencyinjection_7',['DependencyInjection',['../namespace_n_substitute_1_1_core_1_1_dependency_injection.html',1,'NSubstitute::Core']]],
  ['nsubstitute_3a_3acore_3a_3aevents_8',['Events',['../namespace_n_substitute_1_1_core_1_1_events.html',1,'NSubstitute::Core']]],
  ['nsubstitute_3a_3acore_3a_3asequencechecking_9',['SequenceChecking',['../namespace_n_substitute_1_1_core_1_1_sequence_checking.html',1,'NSubstitute::Core']]],
  ['nsubstitute_3a_3aexceptionextensions_10',['ExceptionExtensions',['../namespace_n_substitute_1_1_exception_extensions.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3aexceptions_11',['Exceptions',['../namespace_n_substitute_1_1_exceptions.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3aextensions_12',['Extensions',['../namespace_n_substitute_1_1_extensions.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3aproxies_13',['Proxies',['../namespace_n_substitute_1_1_proxies.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3aproxies_3a_3acastledynamicproxy_14',['CastleDynamicProxy',['../namespace_n_substitute_1_1_proxies_1_1_castle_dynamic_proxy.html',1,'NSubstitute::Proxies']]],
  ['nsubstitute_3a_3aproxies_3a_3adelegateproxy_15',['DelegateProxy',['../namespace_n_substitute_1_1_proxies_1_1_delegate_proxy.html',1,'NSubstitute::Proxies']]],
  ['nsubstitute_3a_3areceivedextensions_16',['ReceivedExtensions',['../namespace_n_substitute_1_1_received_extensions.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3areturnsextensions_17',['ReturnsExtensions',['../namespace_n_substitute_1_1_returns_extensions.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3arouting_18',['Routing',['../namespace_n_substitute_1_1_routing.html',1,'NSubstitute']]],
  ['nsubstitute_3a_3arouting_3a_3aautovalues_19',['AutoValues',['../namespace_n_substitute_1_1_routing_1_1_auto_values.html',1,'NSubstitute::Routing']]],
  ['nsubstitute_3a_3arouting_3a_3ahandlers_20',['Handlers',['../namespace_n_substitute_1_1_routing_1_1_handlers.html',1,'NSubstitute::Routing']]]
];
